### ISSUE TITLE
Analytics: Add full story to webite

### ISSUE THREAD

**Issue by kevinmirc** [ncma-chapters/team#27] opened 2020-03-02 20:52 UTC
Relates to #5

**Comment by kelsonic** [comment] 2020-03-03 16:13
I think this is a duplicate of https://github.com/ncma-chapters/team/issues/23

**Comment by kelsonic** [comment] 2020-03-03 16:25
Closing in favor of https://github.com/ncma-chapters/team/issues/23

**Closed as completed by kelsonic** 2020-03-03 16:25 UTC
Labels: enhancement, ncma-chapter-web
